# Generated by Django 5.1.3 on 2024-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='objetivo',
            field=models.CharField(max_length=500),
        ),
    ]
