# Generated by Django 5.1.3 on 2024-12-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_equipo_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='objetivo',
            field=models.TextField(),
        ),
    ]
